"""empty message

Revision ID: 76e6f6d3c0fb
Revises: 5c32704a30bb
Create Date: 2020-01-09 22:06:42.540049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e6f6d3c0fb'
down_revision = '5c32704a30bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_staff', sa.Column('product_pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_staff', 'product_pic')
    # ### end Alembic commands ###
